feat: add delayUpdate prop
probablykasper/date-picker-svelte pull request #18
Opened 2022-07-17 17:39 UTC by e0

This is aimed to resolve #15, so that when the year or month is changed, the date input does not immediately change. In addition the date input also does not change when the user uses the arrow keys in the date picker. With this change, the only time when the date picker would update the date input is when the user clicks on a date or presses the `Enter` key, given that the new `delayUpdate` property is set to `true` (`false` by default so it does not interfere with the current functionality).

@probablykasper please let me know if this is something you are interested in merging in. I'm happy to make additional changes.

2022-07-17 20:37 UTC, probablykasper commented
Thanks for the PR, appreciate it!

I think the implementation here could be improved. When you go to a new month/year, it still highlights a date in that month, which makes it look like that date is selected even though it isn't. I also think this property should exist in `DatePicker`, not just `DateInput`.

I'd change the name `delayUpdate`, though it's a bit hard to think of a good name. Maybe `browseWithoutSelecting`?

2022-07-17 20:57 UTC, e0 commented
Thanks for the feedback @probablykasper! Nice that you spotted the problem with the date still being highlighted. I like the name change suggestion as well. Will try to fix these now.

2022-07-17 22:25 UTC, e0 commented
I have made some updates to the `DatePicker` now. Not sure about the implementation and if you want to see anything changed, please let me know.

In terms of functionality, no calendar days should be highlighted now when changing month/year. The exception is when changing via the `keydown` events since it feels the most intuitive, for example when pressing the `Left` key when the currently highlighted date is `2022-01-01`.

2022-07-17 22:50 UTC, probablykasper commented
Nice, that seems good. It's a bit bugged though, the `value` still updates sometimes when you switch month/year

2022-07-17 23:36 UTC, e0 commented
I was wondering if that would be the correct behavior. For example, if the year is changed using the select, I thought it would be more straightforward to still change the `value` but not highlight it so that when pressing one of the arrow keys would select a date in the currently displayed month. I think I was still ignoring the fact that the `DatePicker` can used as a standalone component without the `DateInput` though. I will try to have another look at this. Thanks again!

2022-07-18 00:19 UTC, probablykasper commented
The `value` is what you actually use for example if you send a form, so it has to be in sync with what the `DateInput` shows

2022-07-18 00:52 UTC, e0 commented
That makes a lot of sense. I added a guard in the `updateShownDate` function now to conditionally update the `value`. I'm not too sure if I understood the purpose of `shownDate` so please let me know if there is some unwanted side-effects from this.

2022-07-25 05:07 UTC, probablykasper requested changes

2022-07-25 05:07 UTC, probablykasper commented on src/lib/DatePicker.svelte
> +    if (!browseWithoutSelecting && value && shownDate.getTime() !== value.getTime()) {
This has some unintended consequences.

`updateShownDate` is used to clamp the value within the `min` and `max` dates. So if you have `browseWithoutSelecting`, and you update the `min` date, you can now end up with a date that's outside the desired range.

It also makes it so selecting dates with the arrow keys doesn't work with `browseWithoutSelecting` (could be other things too, I haven't checked everything)

2022-07-25 05:12 UTC, probablykasper commented
Could we maybe just use `shownDate` instead of having `highlightedDate`?

2022-07-28 15:45 UTC, e0 commented on src/lib/DateInput.svelte
> +    innerStore.set(value)
Absolutely. This should have been removed in an earlier commit after the logic was added in the `DatePicker`.

2022-07-28 15:50 UTC, e0 commented
> Could we maybe just use `shownDate` instead of having `highlightedDate`?

Thanks for the review. Simply using `shownDate` directly does not work from what I tried as it still changes for example when browsing with arrow keys. I think it is possible to rewrite things so that only `shownDate` is used. I think I need to have a more thorough understanding of things to make sure that I don't break anything (for example as you mentioned [here](https://github.com/probablykasper/date-picker-svelte/pull/18#discussion_r928473763)). I'm not sure when I would have the time to do this though. Would you rather that I close the PR for now and open it up again in the future?

2022-07-30 08:47 UTC, probablykasper commented
I tried my hand at it in PR #18

2022-07-31 15:55 UTC, merged